# Site settings
title: Strikeskids.com
email: webmaster@strikeskids.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://strikeskids.com" # the base hostname & protocol for your site
github_username:  Strikeskids

permalink: /blog/v3/:year/:month/:day/:title

exclude:
  - conf
  - bin

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown: kramdown

gems:
  - "octopress-autoprefixer"
