# Site settings
title: Strikeskids.com
email: webmaster@strikeskids.com
description: A blog about technology and topics that raise my ire
baseurl: ""
url: "https://www.strikeskids.com"
github_username:  Strikeskids

permalink: /blog/v3/:year/:month/:day/:title

exclude:
  - conf
  - bin

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true

plugins:
  - "octopress-autoprefixer"
